wandb_version: 1

batch_size:
  desc: null
  value: 8
num_epochs:
  desc: null
  value: 30
lr:
  desc: null
  value: 0.0001
seq_len:
  desc: null
  value: 350
d_model:
  desc: null
  value: 512
datasource:
  desc: null
  value: opus_books
lang_src:
  desc: null
  value: en
lang_tgt:
  desc: null
  value: it
model_folder:
  desc: null
  value: weights
model_basename:
  desc: null
  value: tmodel_
preload:
  desc: null
  value: null
tokenizer_file:
  desc: null
  value: tokenizer_{0}.json
experiment_name:
  desc: null
  value: runs/tmodel
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.40.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717419801.618672
    t:
      1:
      - 1
      - 11
      - 15
      - 40
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 15
      - 40
      - 49
      - 51
      - 55
      3:
      - 7
      - 16
      - 23
      4: 3.9.18
      5: 0.16.0
      6: 4.40.0
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
